src/BookShop.Web/Areas/Admin/Pages/Files/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookShop.Web.Areas.Admin.Pages.Files
{
    public class IndexModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        public IndexModel(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public IList<FileInfo> FileList { get; set; }
        public void OnGet()
        {
            FileList=new List<FileInfo>();
            var path = Path.Combine(_webHostEnvironment.ContentRootPath, "Files");
            var files=System.IO.Directory.GetFiles(path);
            foreach (var file in files)
            {
                FileList.Add(new FileInfo(file));
            }
        }

        public IActionResult OnGetDownload(string fileName)
        {
            var path = Path.Combine(_webHostEnvironment.ContentRootPath, "Files",fileName);
            var content = System.IO.File.ReadAllBytes(path);
            return File(content,"application/pdf", fileName);
        }
    }
}

src/BookShop.Web/Areas/Admin/Pages/Files/Upload.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookShop.Web.Areas.Admin.Pages.Files
{
    public class UploadModel : PageModel
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        public UploadModel(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }
        [BindProperty]
        public IFormFile ContentFile { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (ContentFile != null)
            {
                using var ms1= new MemoryStream();
                ContentFile.CopyTo(ms1);
                ms1.Position= 0;
                var path = Path.Combine(_webHostEnvironment.ContentRootPath, "Files", ContentFile.FileName);
                using var stream=System.IO.File.Create(path);
                stream.Position= 0;
                await ContentFile.CopyToAsync(stream);
            }
            return RedirectToPage("./Index");
        }
    }
}

src/BookShop.Web/Controllers/FileController.cs
using BookShop.Application;
using BookShop.Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookShop.Web.Controllers
{
    //[Route("api/[controller]")]
    //[ApiController]
    public class FileController : ControllerBase
    {
        private readonly IBookService _bookService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IOrderService _orderService;
        public FileController(IBookService bookService,IOrderService orderService ,IWebHostEnvironment webHostEnvironment)
        {
            _bookService = bookService;
            _webHostEnvironment = webHostEnvironment;
            _orderService = orderService;
        }

        [Authorize]
        [Route("api/book/download/{bookid}")]
        public IActionResult Download(int bookId) //REST GET
        {
            var UserIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var CurrentUserId = UserIdClaim.Value;

            var order=_orderService.GetUserBook(CurrentUserId, bookId);

            if (order is not null)
            {
                var book = _bookService.GetDetails(bookId);
                var path = Path.Combine(_webHostEnvironment.ContentRootPath, "Files", book.FileName);
                var content = System.IO.File.ReadAllBytes(path);

                return File(content, "application/pdf", book.FileName);
            }
             return NotFound();
        }
    }
}

src/BookShop.Web/Areas/Admin/Pages/Files/Index.cshtml
@page
@model BookShop.Web.Areas.Admin.Pages.Files.IndexModel
@{
}

<a asp-page="./upload" class="btn btn-primary">Upload a new File</a>
<table class="table">
    <thead>
        <tr>

            <th>Name</th>
            <th>Size</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var file in Model.FileList)
        {
            <tr>
                <td>@file.Name</td>
                <td>@(file.Length/(1024*1024))MB</td>
                <td>
                    <a asp-page="index" asp-page-handler="download" asp-route-filename="@file.Name" class="btn btn-primary">Download</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/BookShop.Web/Areas/Admin/Pages/Files/Upload.cshtml
@page
@model BookShop.Web.Areas.Admin.Pages.Files.UploadModel
@{
    ViewData["title"] = "Upload";
}

<div class="row">
    <div class="col-md-4">
        <form method="post" class="p-3" enctype="multipart/form-data">
            <div class="form-control">
                <label asp-for="ContentFile" class="form-label"></label>
                <input asp-for="ContentFile" type="file" class="form-control" />
                <span asp-validation-for="ContentFile" class="text-danger"></span>
            </div>
            <div class="form-control">
                <input type="submit" value="Upload" class="btn btn-primary" />
                <a asp-page="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}